# Generated by Django 5.1.3 on 2024-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exercise_ex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_entry',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='food_entry',
            name='description',
            field=models.CharField(max_length=31),
        ),
    ]
